core/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login, logout
from django.conf.urls import patterns, include, url
from .views import TemplateIndexView, TodoEntryFormView, TemplateListView, register_user

urlpatterns = patterns('',
    url(r'^$', login_required(TemplateIndexView.as_view()), name='index'),
    url(r'^list', TemplateListView.as_view(), name="list"),
    url(r'^add_todo/$', TodoEntryFormView.as_view(), name="add_todo"),
    url(r'^login/$', login, {'template_name':"core/login.html"}, name="login_user"),
    url(r'^logout/$', logout, {'next_page': '/'}, name="logout_user"),
    url(r'^register/$', register_user, name="register_user"),
)

pas/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

from tastypie.api import Api
from core.views import EntryResource, UserResource

v1_api = Api(api_name='v1')
v1_api.register(EntryResource())
v1_api.register(UserResource())


urlpatterns = patterns('',
    url(r'', include('core.urls', namespace='core')),
    url(r'^api/', include(v1_api.urls)),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
# encoding: utf-8

from tastypie.models import create_api_key

from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

PRIORITY = (
    (0, 'Low'),
    (1, 'Normal'),
    (2, 'High'),
    (3, 'Urgent')
)

class TodoEntry(models.Model):
    """
    Class for the todo list entry
    """
    title = models.CharField(max_length=255, verbose_name=_('Enter what to do'))
    due_date = models.DateField(verbose_name=_('Due date'))
    priority = models.IntegerField(default=1)
    order = models.IntegerField(default=0)
    is_completed = models.BooleanField(default=False)
    user = models.ForeignKey(User)

    def __unicode__(self):
        return u'{.title}'.format(self)

    def to_json(self):
        return {
            'id': self.pk,
            'title': self.title,
            'due_date': self.due_date,
            'priority': self.priority,
            'order': self.order,
            'is_completed': self.is_completed
        }


models.signals.post_save.connect(create_api_key, sender=User)

core/forms.py
from django import forms

from .models import TodoEntry, PRIORITY

class TodoEntryForm(forms.ModelForm):
    """
    Todo Entry Form
    """
    form_name = 'entry_form'
    priority = forms.ChoiceField(choices=PRIORITY)

    def __init__(self, *args, **kwargs):
        kwargs.update(scope_prefix='entry')
        super(TodoEntryForm, self).__init__(*args, **kwargs)

    class Meta:
        model = TodoEntry
        fields = ('title', 'due_date', 'priority')

core/views.py
# encoding: utf-8
from tastypie.resources import ModelResource
from tastypie.models import ApiKey
from tastypie import fields
from tastypie.authorization import Authorization
from tastypie.authentication import SessionAuthentication, ApiKeyAuthentication, MultiAuthentication

from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.views.generic import TemplateView
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm

from .models import TodoEntry


class TemplateIndexView(TemplateView):
    template_name = 'core/index.html'

    def get_context_data(self, **kwargs):
        context = super(TemplateIndexView, self).get_context_data(**kwargs)
        context['user'] = self.request.user
        return context

class TemplateListView(TemplateView):
    template_name = 'core/list.html'

    def get_context_data(self, **kwargs):
        context = super(TemplateListView, self).get_context_data(**kwargs)
        context['user'] = self.request.user
        return context

class TodoEntryFormView(TemplateView):
    template_name = 'core/add.html'


class UserResource(ModelResource):
    class Meta:
        queryset = User.objects.all()
        resource_name = 'users'
        authentication = MultiAuthentication(
            SessionAuthentication(),
            ApiKeyAuthentication()
        )
        authorization = Authorization()



class EntryResource(ModelResource):

    user = fields.ToOneField(UserResource, 'user')

    class Meta:
        queryset = TodoEntry.objects.all().order_by('order')
        resource_name = 'entries'
        authentication = MultiAuthentication(
            SessionAuthentication(),
            ApiKeyAuthentication()
        )
        authorization = Authorization()

    def obj_create(self, bundle, **kwargs):
        return super(EntryResource, self).obj_create(bundle, user=bundle.request.user)

    def get_object_list(self, request):
        return super(EntryResource, self).get_object_list(request).filter(ser=request.user)



def register_user(request):
    form = UserCreationForm(request.POST or None)
    if form.is_valid():
        username = form.clean_username()
        password = form.clean_password2()
        form.save()
        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect(reverse('core:index'))
    return render(request, 'core/register.html', {'form': form})

pas/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html ng-app="todo">
<head>
    <meta charset="utf-8">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    {% block css %}{% endblock %}
</head>
<body>
   {% block content %}{% endblock %}
   <script src="{% static 'js/jquery.js' %}" type="text/javascript"></script>
   <script src="{% static 'js/jquery-ui.custom.js' %}" type="text/javascript"></script>
   <script src="{% static 'js/angular.min.js' %}"></script>
   {% block js %}{% endblock %}
</body>
</html>

pas/templates/core/add.html
    <form name="todoForm" role="form" novalidate>
        <div class="form-group controls" ng-class="{error: todoForm.name.$invalid}">
          <label for="title">What to do</label>
          <input type="text" name="title" ng-model="entry.title" class="form-control" required>
          <span ng-show="todoForm.title.$error.required" class="help-block">
              Required</span>
        </div>

        <div class="form-group controls" ng-class="{error: todoForm.due_date.$invalid}">
          <label for="due_date">Due date</label>
          <div name="due_date" ng-model="entry.due_date" required ui-date="dateOptions" ui-date-format="yy-mm-dd"></div>
          <span ng-show="todoForm.due_date.$error.required" class="help-block">
              Required</span>
        </div>

        <div class="form-group controls" ng-class="{error: todoForm.priority.$invalid}">
            <label>Priority</label>
            <select class="form-control" name="priority" id="priority" ng-model="entry.priority">
                <option value="0">Low</option>
                <option value="1">Normal</option>
                <option value="2">High</option>
                <option value="3">Urgent</option>
            </select>
            <span ng-show="todoForm.priority.$error.required" class="help-block">
              Required</span>
        </div>

        <div class="btn-group">
            <a href="#/" class="btn">Cancel</a>
        </div>
        <div class="btn-group">
            <button ng-click="saveEntry()" ng-disabled="isClean() || todoForm.$invalid"
                class="btn btn-primary">Save</button>
        </div>
        <div class="btn-group">
            <button ng-click="removeEntry()"
                ng-show="entry.id" class="btn btn-danger">Delete</button>
        </div>
      </form>

pas/templates/core/index.html
{% extends "base.html" %}

{% load staticfiles %}
{% load i18n %}

{% block content %}


    <div class="container">
        <div class="page-header">
            <h1>Simple Todo App</h1>
            <p class="lead">Uses angular.js, restangular and django-tastypie.</p>

            {% if user.is_authenticated %}
                Welcome, {{ user.username }}!
                <a class="btn btn-default" href="{% url 'core:logout_user' %}">Logout</a>
                <span>API KEY is : {{ user.api_key }}</span>
            {% endif %}
        </div>
        <div ng-view><img src="{% static 'img/throbber.gif' %}" /></div>
    </div>
{% endblock %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
{% endblock %}

{% block js %}
    <script src="{% static 'js/underscore-min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/restangular.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/angular-route.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/angular-cookies.js' %}"></script>
    <script src="{% static 'js/sortable.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/date.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/todo.js' %}" type="text/javascript"></script>
{% endblock %}

pas/templates/core/list.html
<div class="container">

    <a href="#/new" class="btn btn-default btn-primary"><span class="glyphicon glyphicon-plus"></span> Add todo</a>

    Filter: <input type="text" ng-model="search" class="search-query" placeholder="Search">

    Sort by:
    <div class="btn-group">
        <button class="btn btn-default btn-primary" ng-click="ordering('due_date')"><span class="glyphicon glyphicon-sort"></span> Due date</button>
        <button class="btn btn-default btn-primary" ng-click="ordering('priority')"><span class="glyphicon glyphicon-sort"></span> Priority</button>
    </div>

    <table class="table">
        <thead>
            <tr>
                  <th>Title</th>
                  <th>Due date</th>
            </tr>
        </thead>
        <tbody ui-sortable="todoSortable" ng-model="entries">
        {% verbatim %}
            <tr
                ng-repeat="entry in entries | filter:{title:search} | orderBy: orderProperty: orderDirection"
                ng-show="entry"
                ng-class="{'bg-success': entry.priority == 0, 'bg-active': entry.priority == 1, 'bg-warning': entry-priority == 2, 'bg-danger': entry.priority == 3}">
                <td><input type="checkbox" ng-model="entry.is_completed" ng-change="completeTodo(entry)" /></td>
                <td>{{entry.title}}</td>
                <td>{{entry.due_date}}</td>
                <td>
                    <a href="#/edit/{{entry.id}}"><i class="glyphicon-pencil glyphicon"></i></a>
                </td>
            </tr>
        </tbody>
    </table>
</div>
{% endverbatim %}

pas/templates/core/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
      <form class="form-signin" role="form" action="" method="post">
        {% csrf_token %}
        {% if form.non_field_errors %}
          <div class="alert alert-warning alert-dismissable">
            {% for error in form.non_field_errors %}
                <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% endif %}
        <h2 class="form-signin-heading">Please sign in</h2>
        <div class="form-group {% if form.username.errors %}has-error{% endif %}">
            <input type="text" class="form-control" placeholder="Login" name="username" required autofocus>
        </div>
        <div class="form-group {% if form.password.errors %}has-error{% endif %}">
            <input type="password" class="form-control" placeholder="Password" name="password" required>
        </div>
        <div class="form-group">
            <button class="btn btn-lg btn-primary" type="submit">Sign in</button>
            <a class="btn" href="{% url 'core:register_user' %}">or Register</a>
        </div>

      </form>
    </div>
{% endblock %}

pas/templates/core/register.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
      <form class="form-signin" role="form" method="post">
        {% csrf_token %}
        <h2 class="form-signin-heading">Please sign up</h2>
        {{ form.username.errors }}
        <input type="text" class="form-control" name="username" placeholder="Login" value="{{ form.username.value|default_if_none:'' }}" required autofocus />
        {{ form.password1.errors }}
        <input type="password" class="form-control" name="password1" placeholder="Password" required />
        {{ form.password2.errors }}
        <input type="password" class="form-control" name="password2" placeholder="Repeat password" required />
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>
      </form>
    </div>
{% endblock %}